version: '3'
services:
   app:
      container_name: docker-node-mongo
      tty: true
      build: .
      ports:
         - '80:3000'
      links:
         - mongodb
   
   mongodb:
    image: mongo  # dockerhub를 사용하는 경우 mongo:버전
    restart: always
    ports:
      - "27017:27017"  # 동일하게 사용하려는 경우 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./mongo-data:/data/db # 현재 경로 하위에 생성하면 ./mongo-data:/data/db

   mongo-express:
    image: mongo-express  # dockerhub를 사용하는 경우 mongo-express:버전
    restart: always
    ports:
      - "8081:8081"  # 동일하게 사용하려는 경우 8081:8081로 지정
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb  # mongodb 컨테이너 이름
      - ME_CONFIG_MONGODB_PORT=27017  # mongodb 연결 포트
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo  # mongodb 컨테이너의 root 계정
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo  # mongodb 컨테이너의 root 비밀번호
      - ME_CONFIG_BASICAUTH_USERNAME=mongo  # mongo-express 사용자 계정
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo  # mongo-express 사용자 비밀번호
      # ME_CONFIG_MONGODB_ENABLE_ADMIN=true  # 모든 데이터베이스에 관리자권한으로 연결 (기본값 true)
    depends_on:
      - mongodb